name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    name: Nix Flake Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run Nix Checks
        run: nix flake check --print-build-logs
